### ISSUE TITLE
Remove China Specific apps and functions

### ISSUE THREAD

**Issue by josephasmith1** [quintus-lab/Openwrt-R2S#6]
Would you consider an 'international/US' version that removes the China specific apps and features? I can contribute with documentation and translation if interested as well as testing.

**Comment by quintus-lab** [comment]
openwrt i18n only has 'en [ English ]' , not 'international/US' package.
zh-cn or zh-tw is unnecessary language packs, removes just for simplicity, not for specific or features.
Thank you for your advice!

**Comment by josephasmith1** [comment]
Sorry my mistake, I wasn't clear in explaining. Since your build is English build, I meant to make a branch that excludes the packages like JD DailyBonus, gost, clash, smart dns, and other proxy apps that are more useful for China internet users.

**Comment by quintus-lab** [comment]
Can modify the 'origin-slim.seed' or '18.06.seed' to remove those apps, such as "CONFIG_PACKAGE_luci-app-jd-dailybonus=y" --> "CONFIG_PACKAGE_luci-app-jd-dailybonus is not set" .

**Comment by josephasmith1** [comment]
Tried to fork and test a config edit as you described, but it failed with 'credentials' error. Would you consider letting a seed build alongside 18.06.seed and origin-slim.seed?

**Comment by quintus-lab** [comment]
purge version for trial, no more China apps.
[https://github.com/quintus-lab/Openwrt-R2S/blob/master/seed/purge-slim.seed](url)

**Comment by josephasmith1** [comment]
Thank you for doing this seed. I did notice a few things. 

-On the ext4 version, the overlay only mounts in the root at 900mb, not using the full SD card, but the squashfs version works as expected. The ttyd app in luci doesn't load. 

-I also had random reboots several times. The only thing I could see in the logs was  "error connecting to ocserv socket '/var/run/occtl.socket':"  I tried changing the governor and enabling/disabling SFE and software offloading, but still had reboots. Will try to get a log file that persists reboot to see if I can isolate the cause of the reboot. The performance is very good so far.

**Comment by josephasmith1** [comment]
Also, just noticed that the squashfs version still has the China apps in the image, but the ext4 does not.

**Comment by quintus-lab** [comment]
please wipe out your TF card before write image into

**Comment by josephasmith1** [comment]
Definitely did that, and just to double check, I looked on the image file.
When I open up the image file, those apps are in the file.

**Comment by josephasmith1** [comment]
Well this is strange, but I downloaded the image from 10-16, and it did not build with those apps, but the images just as recently as 10-15 had the apps in the build. What would cause that?
![image](https://user-images.githubusercontent.com/6611890/96319785-7f152c00-0fc5-11eb-8eea-865ca22392e6.png)
![image](https://user-images.githubusercontent.com/6611890/96319831-95bb8300-0fc5-11eb-9496-63be30d4a6fb.png)

**Comment by josephasmith1** [comment]
Did purge-slim stop building?
